// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package license

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/fr4nsys/usulnet/internal/web/templates/layouts"
)

// LicensePageInfo holds the current license state for the template.
// The Edition / EditionName fields tag the support tier carried on a
// commercial license token; they are display-only and never gate any
// feature in the AGPL build.
type LicensePageInfo struct {
	Edition     string
	EditionName string
	LicenseID   string
	Status      string // "active" | "expired" | "invalid" | "none"
	ExpiresAt   string
	ActivatedAt string
	InstanceID  string
	Hostname    string
	MaxNodes    int
	MaxUsers    int
}

// LicensePageData holds data for the license page.
type LicensePageData struct {
	PageData layouts.PageData
	License  LicensePageInfo
}

func statusBadge(status string) string {
	switch status {
	case "active":
		return "bg-green-500/10 text-green-400 border-green-500/20"
	case "expired":
		return "bg-red-500/10 text-red-400 border-red-500/20"
	case "invalid":
		return "bg-red-500/10 text-red-400 border-red-500/20"
	default:
		return "bg-gray-500/10 text-gray-400 border-gray-500/20"
	}
}

// hasCommercialToken returns true when the operator has activated a
// commercial support token (so the activate/deactivate flow shows the
// "update / deactivate" copy instead of "activate").
func hasCommercialToken(info LicensePageInfo) bool {
	return info.LicenseID != "" && info.Status != ""
}

func LicensePage(data LicensePageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-6 max-w-6xl mx-auto\"><!-- Header --><div><h1 class=\"text-2xl font-bold text-white\"><i aria-hidden=\"true\" class=\"fas fa-id-card mr-2 text-primary-400\"></i> License Management</h1><p class=\"text-gray-400 mt-1\">usulnet ships under AGPL-3.0-or-later. Every feature is available unconditionally — see CHANGELOG &ldquo;Open and unlimited&rdquo;.</p></div><!-- Edition Card --><div class=\"bg-dark-800 border border-dark-700 rounded-xl p-6\"><div class=\"flex items-start justify-between flex-wrap gap-4\"><div class=\"flex items-center gap-4\"><div class=\"w-14 h-14 rounded-xl flex items-center justify-center bg-primary-500/10\"><i aria-hidden=\"true\" class=\"fas fa-infinity text-2xl text-primary-400\"></i></div><div><h2 class=\"text-xl font-bold text-white\">usulnet · AGPL build</h2><div class=\"flex items-center gap-3 mt-1 flex-wrap\"><span class=\"inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium bg-green-500/10 text-green-400 border border-green-500/20\"><i aria-hidden=\"true\" class=\"fas fa-check-circle\"></i> All features unlocked</span> <span class=\"inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium bg-dark-700 text-gray-400 border border-dark-600\">AGPLv3</span> <span class=\"text-sm text-gray-500\">Unlimited nodes &middot; users &middot; backups</span></div></div></div></div></div><!-- Instance Info + Optional Support Token --><div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\"><!-- Instance Information --><div class=\"bg-dark-800 border border-dark-700 rounded-xl p-6\"><h3 class=\"text-sm font-medium text-gray-400 uppercase tracking-wider mb-4\"><i aria-hidden=\"true\" class=\"fas fa-server mr-2\"></i> Instance Information</h3><dl class=\"space-y-3\"><div class=\"flex items-center justify-between py-1\"><dt class=\"text-sm text-gray-500\">Instance ID</dt><dd class=\"text-sm text-white font-mono\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.License.InstanceID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/license/page.templ`, Line: 100, Col: 73}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</dd></div><div class=\"flex items-center justify-between py-1\"><dt class=\"text-sm text-gray-500\">Hostname</dt><dd class=\"text-sm text-white\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(data.License.Hostname)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/license/page.templ`, Line: 104, Col: 61}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</dd></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.License.LicenseID != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"flex items-center justify-between py-1\"><dt class=\"text-sm text-gray-500\">Support token ID</dt><dd class=\"text-sm text-white font-mono\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(data.License.LicenseID)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/license/page.templ`, Line: 109, Col: 73}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</dd></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if data.License.ActivatedAt != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"flex items-center justify-between py-1\"><dt class=\"text-sm text-gray-500\">Activated</dt><dd class=\"text-sm text-white\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(data.License.ActivatedAt)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/license/page.templ`, Line: 115, Col: 65}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</dd></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if data.License.ExpiresAt != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div class=\"flex items-center justify-between py-1\"><dt class=\"text-sm text-gray-500\">Support expires</dt><dd class=\"text-sm text-white\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(data.License.ExpiresAt)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/license/page.templ`, Line: 121, Col: 63}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</dd></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if hasCommercialToken(data.License) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div class=\"flex items-center justify-between py-1\"><dt class=\"text-sm text-gray-500\">Support status</dt><dd>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var8 = []any{"inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium border", statusBadge(data.License.Status)}
				templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var8...)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<span class=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var9 string
				templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var8).String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/license/page.templ`, Line: 1, Col: 0}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if data.License.Status == "active" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<i aria-hidden=\"true\" class=\"fas fa-check-circle\"></i> ")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<i aria-hidden=\"true\" class=\"fas fa-exclamation-circle\"></i> ")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				var templ_7745c5c3_Var10 string
				templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(data.License.Status)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/license/page.templ`, Line: 134, Col: 31}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</span></dd></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</dl></div><!-- Optional commercial support token --><div class=\"bg-dark-800 border border-dark-700 rounded-xl p-6\"><h3 class=\"text-sm font-medium text-gray-400 uppercase tracking-wider mb-4\"><i aria-hidden=\"true\" class=\"fas fa-key mr-2\"></i> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if hasCommercialToken(data.License) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "Update Support Token")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "Activate Support Token (optional)")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</h3><p class=\"text-xs text-gray-500 mb-3\">Activation is optional. A commercial support token does not unlock additional runtime features — every feature is already available — it only records the support contract carried by the operator.</p><form method=\"post\" action=\"/license/activate\" class=\"space-y-4\"><input type=\"hidden\" name=\"csrf_token\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(data.PageData.CSRFToken)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/license/page.templ`, Line: 156, Col: 76}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "\"><div><label class=\"block text-sm text-gray-400 mb-2\">Support token (JWT)</label> <textarea name=\"license_key\" placeholder=\"eyJhbGciOiJSUzUxMiIs...\" required rows=\"4\" class=\"w-full bg-dark-700 border border-dark-600 rounded-lg text-white px-3 py-2.5 text-xs font-mono placeholder-gray-500 focus:border-primary-500 focus:ring-1 focus:ring-primary-500 resize-none\"></textarea></div><button type=\"submit\" class=\"w-full bg-primary-500 hover:bg-primary-600 text-black font-medium px-4 py-2.5 rounded-lg transition-colors\"><i aria-hidden=\"true\" class=\"fas fa-check mr-2\"></i> Activate</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if hasCommercialToken(data.License) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "<form method=\"post\" action=\"/license/deactivate\" class=\"mt-3\"><input type=\"hidden\" name=\"csrf_token\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var12 string
				templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(data.PageData.CSRFToken)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/license/page.templ`, Line: 174, Col: 77}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "\"> <button type=\"submit\" class=\"w-full text-sm text-gray-500 hover:text-red-400 transition-colors py-2\"><i aria-hidden=\"true\" class=\"fas fa-times mr-1\"></i> Remove support token</button></form>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base(data.PageData).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
